image:
  file: .gitpod.dockerfile
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: true
    addBadge: false
    addLabel: false
tasks:
- command: |
    mkdir -p /home/gitpod/.android
    touch /home/gitpod/.android/repositories.cfg
    export PATH=/usr/lib/dart/bin:$FLUTTER_HOME/bin:$ANDROID_HOME/bin:$PATH
    /home/gitpod/android-sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3"
vscode:
  extensions:
    - Dart-Code.flutter@3.5.0:/kOacEWdiDRLyN/idUiM4A==
