# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'BertQA-UIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BertQA
  pod 'TensorFlowLiteSwift', '0.0.1-nightly'
end

target 'BertQA-SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BertQA
  pod 'TensorFlowLiteSwift', '0.0.1-nightly'
end
