# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'BertQA-UIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BertQA-UIKit
  pod 'TensorFlowLiteTaskText', '~> 0.2.0'
end

target 'BertQA-SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BertQA-SwiftUI
  pod 'TensorFlowLiteTaskText', '~> 0.2.0'
end
