# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ImageSegmentation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageSegmentation
  pod 'TensorFlowLiteSwift', '0.0.1-nightly'

end
