package(
    default_applicable_licenses = ["//third_party/py/tensorflow_examples:license"],
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],  # Apache 2.0
)

exports_files(glob(["*"]))

filegroup(
    name = "testdata",
    srcs = glob([
        "**/*",
    ]),
)
