# This empty BUILD file is required to make Bazel treat this directory as a package.

package(
    default_applicable_licenses = ["//third_party/py/tensorflow_examples:license"],
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])
