platform :ios, '12.0'

target 'SoundClassification' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly'
  pod 'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'
end
