# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'PoseEstimation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PoseEstimation
  pod 'LiteRTSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal']

end
